### ISSUE TITLE
bash error : No such file or directory

### ISSUE THREAD

**Issue by F-Mirfeizi** [MohammadAminDHM/Filoger#45]
من قدم به قدم با ویدیو پیش رفتم. اینجا با وجودی که تو مسیر درست هستم خطا میده. علت چیه؟

![Capture](https://github.com/MohammadAminDHM/Filoger/assets/134170179/3f3e6395-84ca-44b9-9007-8e66f0b480c9)

**Comment by MohammadAminDHM** [comment]
https://github.com/MohammadAminDHM/Filoger/issues/38#issuecomment-1573608049

این کار رو انجام بدید

**Comment by F-Mirfeizi** [comment]
منظورتون آدرسیه که تو لاین 3 نوشته ؟ یا 8 ؟ چون داره تو لاین 3 ارور میده. البته من هر دو رو گذاشتم داخل کوتیشن جواب نداد.

**Comment by MohammadAminDHM** [comment]
لاین ۱۱ اینطور بزنید
mv "first" .

**Comment by F-Mirfeizi** [comment]
حلش کردم آقای دهملایی مشکل این بود که فولدر MyProject خالی بود و اون دو تا فولدر Bizz-Fizz و Days-of-Week داخلش نبود.

**Comment by F-Mirfeizi** [comment]
و یه مشکل دیگه هم این بود که سیو رو میزدم تغییرات تو کد ذخیره میشد ولی اجرا نمیشد. یک بار کلا ترمینالها و کدها رو بستم دوباره باز کردم این مشکل هم حل شد
