### ISSUE TITLE
".ipynb_checkpoints" deleting

### ISSUE THREAD

**Issue by F-Mirfeizi** [MohammadAminDHM/Filoger#58]
How can I delete ".ipynb_checkpoints" folder in GitHub ?

**Comment by MohammadAminDHM** [comment]
از دستور زیر استفاده کنید

find . -name .ipynb_checkpoints -print0 | xargs -0 git rm -rf --ignore-unmatch
git add .
git commit -m "Remove .ipynb_checkpoints from everywhere"
git push
